### ISSUE TITLE
duration 20 mins or 40 mins

### ISSUE THREAD

**Issue by AngelaQYang** [psrc/data-science#1]
Hi Micheal @jensenmj 

This is a small question regarding the pickup/dropoff trips. I noticed in the notes, it said 20 mins is the threshold. In the code (and the code following), you use 40 mins. Can you confirm it? Thanks! 

Angela

**Comment by jensenmj** [comment]
I definitely consider these up for debate.  The notes use 20, but I find longer instances in the data that aren't exceptional: it's pretty common to take longer picking up a kid from preschool or school.  The parent may stop and talk with a friend or teacher but the purpose is still pick-up.  Some people are NYC busy and some people take their time.  40 minutes, and I think it's clear they came for something more involved.

**Comment by AngelaQYang** [comment]
Sounds good! I will close this issue. Thanks for checking issues!
